FROM golang:latest as builder

WORKDIR /app

COPY client/client.go .
COPY go.sum .
COPY go.mod .
RUN go mod vendor

RUN CGO_ENABLED=0 GO111MODULE=on go build -mod=vendor -v -o client_app .


FROM alpine:latest

WORKDIR /home

COPY --from=builder /app/client_app .

ENTRYPOINT ["./client_app"]
CMD ["-addr=127.0.0.1:7001"]